/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SchoolManagementApp.view;

import AppManajemenSekolah.AppManajemenSekolah;
import java.awt.Cursor;

/**
 *
 * @author asus
 */
public class GuruHomeView extends javax.swing.JPanel {
    private AppManajemenSekolah app;
    /**
     * Creates new form GuruHomeView
     */
    public GuruHomeView(AppManajemenSekolah app) {
        initComponents();
        this.app = app;
        namaGuru.setText("Nama: " + app.sekolah.getGuru(app.CurrentUser).getNamaAwal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ListAbsensi = new javax.swing.JLabel();
        InputNilai = new javax.swing.JLabel();
        namaGuru = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        TambahTugas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tambah Tugas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Input Nilai");

        ListAbsensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/absence.png"))); // NOI18N
        ListAbsensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListAbsensiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ListAbsensiMouseEntered(evt);
            }
        });

        InputNilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/book-and-pen.png"))); // NOI18N
        InputNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputNilaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InputNilaiMouseEntered(evt);
            }
        });

        namaGuru.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        namaGuru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaGuru.setText("My School");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/teachers.png"))); // NOI18N

        btnLogout.setBackground(new java.awt.Color(153, 0, 0));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        TambahTugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/assignment.png"))); // NOI18N
        TambahTugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TambahTugasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TambahTugasMouseEntered(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Absensi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel4))
                        .addComponent(ListAbsensi)))
                .addGap(0, 120, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(namaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(TambahTugas)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(InputNilai))
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(namaGuru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListAbsensi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputNilai, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TambahTugas, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ListAbsensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListAbsensiMouseClicked
        app.showListAbsensiView();
    }//GEN-LAST:event_ListAbsensiMouseClicked

    private void ListAbsensiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListAbsensiMouseEntered
        ListAbsensi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ListAbsensiMouseEntered

    private void InputNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputNilaiMouseClicked
        app.showListNilaiView();
        
    }//GEN-LAST:event_InputNilaiMouseClicked

    private void InputNilaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputNilaiMouseEntered
       InputNilai.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_InputNilaiMouseEntered

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        app.showLoginView();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void TambahTugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TambahTugasMouseClicked
       app.showTambahTugasView();
    }//GEN-LAST:event_TambahTugasMouseClicked

    private void TambahTugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TambahTugasMouseEntered
        TambahTugas.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_TambahTugasMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InputNilai;
    private javax.swing.JLabel ListAbsensi;
    private javax.swing.JLabel TambahTugas;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel namaGuru;
    // End of variables declaration//GEN-END:variables
}
