/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SchoolManagementApp.view;

import AppManajemenSekolah.AppManajemenSekolah;
import AppManajemenSekolah.entity.Absensi;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class InformasiAbsensiView extends javax.swing.JPanel {

    private AppManajemenSekolah app;
    private int kelas;
    private int banyak;
    private DefaultTableModel tableModel;
    private Date tanggalBuat;
    private Date tanggalBerakhir;

    /**
     * Creates new form InformasiAbsensiView
     */
    public InformasiAbsensiView(AppManajemenSekolah app, Date tanggalBuat, Date tanggalBerakhir, int kelas) {
        initComponents();
        this.app = app;
        this.kelas = kelas;
        this.tanggalBuat = tanggalBuat;
        this.tanggalBerakhir = tanggalBerakhir;
               
        tableModel = (DefaultTableModel) ListBelumAbsensi.getModel();
        infoTanggalBuat.setDate(tanggalBuat);
        infoTanggalBerakhir.setDate(tanggalBerakhir);
        infoTanggalBuat.setEnabled(false);
        infoTanggalBerakhir.setEnabled(false);
        infoKelas.setText(Integer.toString(kelas));
        infoKelas.setEnabled(false);
        Dataview();
        infoAbsensi.setText(Integer.toString(app.sekolah.getBanyakSiswaByKelas(kelas)-banyak));
        infoTotalSiswa.setText(Integer.toString(app.sekolah.getBanyakSiswaByKelas(kelas)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        infoAbsensi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        infoTotalSiswa = new javax.swing.JLabel();
        infoTanggalBuat = new com.toedter.calendar.JDateChooser();
        infoTanggalBerakhir = new com.toedter.calendar.JDateChooser();
        infoKelas = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListBelumAbsensi = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Kelas:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tanggal Buat:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tanggal Berakhir:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Total Absensi:");

        infoAbsensi.setText("jLabel5");

        jLabel6.setText("/");

        infoTotalSiswa.setText("jLabel7");

        infoKelas.setText("jLabel8");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("List Yang Belum Absensi");

        ListBelumAbsensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS", "Nama Awal", "Nama Akhir"
            }
        ));
        jScrollPane1.setViewportView(ListBelumAbsensi);

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/back.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(infoTanggalBerakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(infoTanggalBuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(infoAbsensi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(infoTotalSiswa)))
                                .addGap(0, 133, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(infoKelas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKembali))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(infoKelas)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnKembali)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(infoTanggalBuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(infoTanggalBerakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(infoAbsensi)
                    .addComponent(jLabel6)
                    .addComponent(infoTotalSiswa))
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
       app.showListAbsensiView();
    }//GEN-LAST:event_btnKembaliActionPerformed
    public void Dataview() {
        banyak=0;
        for (int i = 0; i < app.sekolah.getJumlahSiswa(); i++) {
            if (app.sekolah.getSiswa(i).getkelas() == kelas) {
                ArrayList<Absensi> daftarAbsensi = app.sekolah.getSiswa(i).getAbsensi();
                for (Absensi absensi : daftarAbsensi) {
                    if (absensi.getTanggalBuat().getTime() == tanggalBuat.getTime() && absensi.getTanggalBerakhir().getTime() == tanggalBerakhir.getTime()
                            && !absensi.getStatus()
                            && absensi.getMatapeljaran().equals(app.sekolah.getGuru(app.CurrentUser).getMataPelajaran())) {
                        tableModel.addRow(new Object[]{
                            app.sekolah.getSiswa(i).getnis(),
                            app.sekolah.getSiswa(i).getNamaAwal(),
                            app.sekolah.getSiswa(i).getNamaAkhir()
                        });
                        banyak++;
                    }

                }
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListBelumAbsensi;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel infoAbsensi;
    private javax.swing.JLabel infoKelas;
    private com.toedter.calendar.JDateChooser infoTanggalBerakhir;
    private com.toedter.calendar.JDateChooser infoTanggalBuat;
    private javax.swing.JLabel infoTotalSiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
