/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SchoolManagementApp.view;

import AppManajemenSekolah.AppManajemenSekolah;
import AppManajemenSekolah.entity.Tugas;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author asus
 */
public class ListTugasView extends javax.swing.JPanel {

    private AppManajemenSekolah app;
    private DefaultTableModel tableModel;
    private int indeks;
    private String nama;

    /**
     * Creates new form ListTugasView
     */
    public ListTugasView(AppManajemenSekolah app) {
        initComponents();
        this.app = app;
        tableModel = (DefaultTableModel) ListTugas.getModel();
        indeks = app.CurrentUser;
        Dataview();
        nama = app.sekolah.getSiswa(indeks).getNamaAwal() + " " + app.sekolah.getSiswa(indeks).getNamaAkhir();
        namaSiswa.setText("Nama: "+ nama);

    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaSiswa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListTugas = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();

        namaSiswa.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        namaSiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaSiswa.setText("My School");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/male-student.png"))); // NOI18N

        ListTugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mata Pelajaran","Nama Tugas","Tanggal Deadline","Status","Nilai"
            }
        ));
        ListTugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListTugasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListTugas);

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/back.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(btnKembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaSiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
 public void Dataview() {
    TableColumn column = ListTugas.getColumnModel().getColumn(2);
    column.setPreferredWidth(150);
    TableColumn column1 = ListTugas.getColumnModel().getColumn(3);
    column1.setPreferredWidth(100);
    ArrayList<Tugas> daftarTugasSiswa = app.sekolah.getSiswa(indeks).getDaftarTugas();
    
    for (Tugas tugas : daftarTugasSiswa) {
        tableModel.addRow(new Object[]{
            tugas.getMataPelajaran(),
            tugas.getNamaTugas(), 
            tugas.getTanggalDeadline(),
            tugas.getStatus(),
            tugas.getNilai()
        });
    }
}

    private void ListTugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListTugasMouseClicked
       int selectedRow = ListTugas.getSelectedRow();
        String matapelajaran = (String) tableModel.getValueAt(selectedRow,0);
        String namaTugas = (String) tableModel.getValueAt(selectedRow, 1);
        Date tanggalDeadline = (Date) tableModel.getValueAt(selectedRow, 2);
        String statusTugas = (String) tableModel.getValueAt(selectedRow, 3);
        File fileTugas = app.sekolah.getSiswa(indeks).getDaftarTugas().get(selectedRow).getFiles();
        if(statusTugas.equals("Belum Terkumpul")||app.sekolah.getSiswa(indeks).getDaftarTugas().get(selectedRow).getFiles()!=null)
        {
        app.showUploadTugasView(app,namaTugas,tanggalDeadline,statusTugas,selectedRow,matapelajaran,fileTugas);
        }
    }//GEN-LAST:event_ListTugasMouseClicked

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        app.showSiswaHomeView();
    }//GEN-LAST:event_btnKembaliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListTugas;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namaSiswa;
    // End of variables declaration//GEN-END:variables
}
