/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SchoolManagementApp.view;

import AppManajemenSekolah.AppManajemenSekolah;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author asus
 */
public class ListSiswaView extends javax.swing.JPanel {
    private AppManajemenSekolah app;
    private DefaultTableModel tableModel;
    private int kelas;
    /**
     * Creates new form ListSiswaView
     */
    public ListSiswaView(AppManajemenSekolah app) {
        initComponents();
        this.app = app;
        tableModel = (DefaultTableModel) ListSiswa.getModel();
        this.kelas = Integer.parseInt((String) inputKelas.getSelectedItem());
        Dataview();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListSiswa = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inputKelas = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("List Siswa");

        ListSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "NIS","Nama Awal", "Nama Akhir","Kelas","Masa Akses"
            }
        ));
        ListSiswa.setShowGrid(true);
        ListSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListSiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListSiswa);

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/back.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(0, 153, 0));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/add.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Kelas:");

        inputKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9" }));

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnTambah)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public void Dataview()
    {
        tableModel.setRowCount(0);
        for(int i=0;i<app.sekolah.getJumlahSiswa();i++)
        {
            if(app.sekolah.getSiswa(i).getkelas() == kelas)
            tableModel.addRow(new Object[]{
                    app.sekolah.getSiswa(i).getnis(),
                    app.sekolah.getSiswa(i).getNamaAwal(),
                    app.sekolah.getSiswa(i).getNamaAkhir(),
                    app.sekolah.getSiswa(i).getkelas(),
                    app.sekolah.getSiswa(i).getTanggalMaksimalAkses()
                });
        }
    }
    private void ListSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListSiswaMouseClicked
       int selectedRow = ListSiswa.getSelectedRow();
       int nis = (int) tableModel.getValueAt(selectedRow,0);
       String namaAwal = (String) tableModel.getValueAt(selectedRow,1);
       String namaAkhir = (String) tableModel.getValueAt(selectedRow, 2);
       int kelas = (int) tableModel.getValueAt(selectedRow,3);
       Date tanggalMaksimalAkses = (Date) tableModel.getValueAt(selectedRow, 4);
       app.showEditSiswaView(nis,namaAwal,namaAkhir,kelas,tanggalMaksimalAkses);
    }//GEN-LAST:event_ListSiswaMouseClicked

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        app.showAdminHomeView();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        this.kelas = Integer.parseInt((String) inputKelas.getSelectedItem());
        Dataview();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        app.showTambahSiswaView();
    }//GEN-LAST:event_btnTambahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListSiswa;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> inputKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
