/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SchoolManagementApp.view;

import AppManajemenSekolah.AppManajemenSekolah;
import AppManajemenSekolah.entity.Tugas;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author asus
 */
public class ListNilaiView extends javax.swing.JPanel {

    private AppManajemenSekolah app;
    private DefaultTableModel tableModel;
    private int indeks;
    private int kelas;
    private String matapelajaran;

    /**
     * Creates new form InputNilaiView
     */
    public ListNilaiView(AppManajemenSekolah app) {
        initComponents();
        this.app = app;
        indeks = app.CurrentUser;
        tableModel = (DefaultTableModel) ListTugas.getModel();
        matapelajaran = app.sekolah.getGuru(indeks).getMataPelajaran();
        kelas = Integer.parseInt((String) inputKelas.getSelectedItem());
        Dataview();
        namaGuru.setText("Nama: " + app.sekolah.getGuru(indeks).getNamaAwal() );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaGuru = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListTugas = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        inputKelas = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        namaGuru.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        namaGuru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaGuru.setText("My School");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/teachers.png"))); // NOI18N

        ListTugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS","Nama","Nama Tugas", "Nilai"
            }
        ));
        ListTugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListTugasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListTugas);

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/back.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        inputKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9" }));

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Kelas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnKembali)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(inputKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(btnKembali))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaGuru)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
       app.showGuruHomeView();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       kelas = Integer.parseInt((String) inputKelas.getSelectedItem());
       Dataview();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void ListTugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListTugasMouseClicked
        int selectedRow = ListTugas.getSelectedRow();
        int nis = (int) tableModel.getValueAt(selectedRow,0);
        String namaTugas = (String) tableModel.getValueAt(selectedRow,2);
        System.out.println(namaTugas);
        int indexSiswa;
        int indexTugas;
        try {
            indexSiswa = app.sekolah.getIndexSiswa(nis);
            indexTugas = app.sekolah.getSiswa(indexSiswa).getIndexTugas(namaTugas);
            System.out.println(indexTugas);
            app.showInputNilaiView(app,indexSiswa,indexTugas);
        } catch (Exception ex) {
            Logger.getLogger(ListNilaiView.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_ListTugasMouseClicked
    public void Dataview() {
    tableModel.setRowCount(0);
    for (int i = 0; i < app.sekolah.getJumlahSiswa(); i++) {
        ArrayList<Tugas> daftarTugasSiswa = app.sekolah.getSiswa(i).getDaftarTugas();
        for (Tugas tugas : daftarTugasSiswa) {
            if (tugas.getMataPelajaran().equals(matapelajaran) && tugas.TelahDikumpulkan() && tugas.getKelas() == kelas && tugas.getNilai()==0) {
                tableModel.addRow(new Object[]{
                    app.sekolah.getSiswa(i).getnis(),
                    app.sekolah.getSiswa(i).getNamaAwal()+ " "+ app.sekolah.getSiswa(i).getNamaAkhir(),
                    tugas.getNamaTugas(),
                    tugas.getNilai()
                });
            }
            
        }
    }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListTugas;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> inputKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namaGuru;
    // End of variables declaration//GEN-END:variables
}
