/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SchoolManagementApp.view;

import AppManajemenSekolah.AppManajemenSekolah;
import AppManajemenSekolah.entity.Absensi;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class ListAbsensiSiswaView extends javax.swing.JPanel {

    private AppManajemenSekolah app;
    private DefaultTableModel tableModel;
    private int tanggal;

    /**
     * Creates new form ListAbsensiSiswaView
     */
    public ListAbsensiSiswaView(AppManajemenSekolah app) {
        initComponents();
        this.app = app;
        tableModel = (DefaultTableModel) ListAbsensi.getModel();
        infoTanggal.setDate(new Date());
        tanggal = infoTanggal.getDate().getDay();
        Dataview();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaSiswa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListAbsensi = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        infoTanggal = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        namaSiswa.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        namaSiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaSiswa.setText("My School");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/male-student.png"))); // NOI18N

        ListAbsensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mata Pelajaran","Tanggal Buat","Tanggal Berakhir"
            }
        ));
        ListAbsensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListAbsensiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListAbsensi);

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/back.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tanggal:");

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(infoTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRefresh)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(btnKembali)
                        .addComponent(btnRefresh))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namaSiswa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(infoTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public void Dataview() {
        tableModel.setRowCount(0);
        ArrayList<Absensi> absensi = app.sekolah.getSiswa(app.CurrentUser).getAbsensi();
        for (Absensi list : absensi) {
            if (list.getTanggalBuat().getDay() == tanggal && !list.getStatus()) {
                tableModel.addRow(new Object[]{
                    list.getMatapeljaran(),
                    list.getTanggalBuat(),
                    list.getTanggalBerakhir()
                });
            }
        }
    }
    private void ListAbsensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListAbsensiMouseClicked
        int selectedRow = ListAbsensi.getSelectedRow();
        Date now = new Date();
        if (!app.sekolah.getSiswa(app.CurrentUser).getAbsensi().get(selectedRow).getStatus()) {
            if(app.sekolah.getSiswa(app.CurrentUser).getAbsensi().get(selectedRow).getTanggalBerakhir().getTime() > now.getTime())
            {
            app.sekolah.getSiswa(app.CurrentUser).getAbsensi().get(selectedRow).setStatus();
            JOptionPane.showMessageDialog(this, "Absensi telah tercatat");
            System.out.println("cek");
            }
            else
            {
                 JOptionPane.showMessageDialog(this, "Absensi gagal, melewati batas waktu");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sudah melakukan Absensi sebelumnya");
        }


    }//GEN-LAST:event_ListAbsensiMouseClicked

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        app.showSiswaHomeView();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        tanggal = infoTanggal.getDate().getDay();
        Dataview();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListAbsensi;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnRefresh;
    private com.toedter.calendar.JDateChooser infoTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namaSiswa;
    // End of variables declaration//GEN-END:variables
}
