/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SchoolManagementApp.view;

import AppManajemenSekolah.AppManajemenSekolah;
import java.awt.Cursor;

/**
 *
 * @author asus
 */
public class SiswaHomeView extends javax.swing.JPanel {
    private AppManajemenSekolah app;
    /**
     * Creates new form SiswaHomeView
     */
    public SiswaHomeView(AppManajemenSekolah app) {
        initComponents();
        this.app = app;
        int indeks = app.CurrentUser;
        namaGuru.setText("Nama: " + app.sekolah.getSiswa(indeks).getNamaAwal() + " " + app.sekolah.getSiswa(indeks).getNamaAkhir());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaGuru = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TambahTugas = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ListAbsen = new javax.swing.JLabel();
        btnEditNama = new javax.swing.JButton();

        namaGuru.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        namaGuru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaGuru.setText("My School");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/male-student.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("List Tugas");

        TambahTugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/conditions.png"))); // NOI18N
        TambahTugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TambahTugasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TambahTugasMouseEntered(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(153, 0, 0));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("List Absen");

        ListAbsen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/absence.png"))); // NOI18N
        ListAbsen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListAbsenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ListAbsenMouseEntered(evt);
            }
        });

        btnEditNama.setBackground(new java.awt.Color(153, 153, 0));
        btnEditNama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenSekolah/asset/edit.png"))); // NOI18N
        btnEditNama.setText("Edit Nama");
        btnEditNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditNamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(namaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(TambahTugas))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(ListAbsen))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogout)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditNama)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(btnLogout)
                    .addComponent(btnEditNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaGuru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ListAbsen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TambahTugas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TambahTugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TambahTugasMouseClicked
        app.showListTugasView();
    }//GEN-LAST:event_TambahTugasMouseClicked

    private void TambahTugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TambahTugasMouseEntered
        TambahTugas.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_TambahTugasMouseEntered

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        app.showLoginView();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void ListAbsenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListAbsenMouseClicked
        app.showListAbsensiSiswaView();
    }//GEN-LAST:event_ListAbsenMouseClicked

    private void ListAbsenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListAbsenMouseEntered
       ListAbsen.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ListAbsenMouseEntered

    private void btnEditNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditNamaActionPerformed
        app.showEditNamaSiswaView();
    }//GEN-LAST:event_btnEditNamaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ListAbsen;
    private javax.swing.JLabel TambahTugas;
    private javax.swing.JButton btnEditNama;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel namaGuru;
    // End of variables declaration//GEN-END:variables
}
