/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SchoolManagementApp.view;

import AppManajemenSekolah.AppManajemenSekolah;
import java.awt.Color;
import java.io.File;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class UploadTugasView extends javax.swing.JPanel {
    private AppManajemenSekolah app;
    private String namaTugas;
    private String matapelajaran;
    private Date tanggalDeadline;
    private String statusTugas;
    private File fileTugas;
    private int selectedRow;
    /**
     * Creates new form UploadTugasView
     */
    public UploadTugasView(AppManajemenSekolah app,String namaTugas,Date tanggalDeadline,String statusTugas,int selectedRow,String matapelajaran,File file) {
        initComponents();
        this.app = app;
        this.namaTugas = namaTugas;
        this.tanggalDeadline = tanggalDeadline;
        this.statusTugas = statusTugas;
        this.selectedRow = selectedRow;
        this.matapelajaran = matapelajaran;
        this.fileTugas = file;
        
        if(fileTugas!=null)
        {
            infoNamaFile.setText(fileTugas.getAbsolutePath());
        }
        infoTanggalTenggat.setEnabled(false);
        infoNamaTugas.setEnabled(false);
        infoMatapelajaran.setEnabled(false);
        infoTanggalTenggat.setDate(tanggalDeadline);
        infoNamaTugas.setText(namaTugas);
        infoMatapelajaran.setText(matapelajaran);
        infoStatus.setText(statusTugas);
        if(statusTugas.equals("Belum Terkumpul"))
        {
            Color customColor = new Color(102,0,0);
            infoStatus.setForeground(customColor);
        }
        else
        {
            Color customColor = new Color(0,102,0);
            infoStatus.setForeground(customColor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        btnKumpul = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        infoNamaTugas = new javax.swing.JTextField();
        infoTanggalTenggat = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        infoMatapelajaran = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        infoStatus = new javax.swing.JLabel();
        uploadTugas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        infoNamaFile = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Upload Tugas");

        btnKumpul.setBackground(new java.awt.Color(51, 102, 0));
        btnKumpul.setForeground(new java.awt.Color(255, 255, 255));
        btnKumpul.setText("Kumpul");
        btnKumpul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKumpulActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tenggat Pengumpulan:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nama Tugas:");

        infoNamaTugas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        infoNamaTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoNamaTugasActionPerformed(evt);
            }
        });

        jLabel4.setText("Pelajaran");

        jLabel5.setText("Status:");

        infoStatus.setBackground(new java.awt.Color(0, 102, 0));
        infoStatus.setText("jLabel6");

        uploadTugas.setText("+");
        uploadTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadTugasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Upload Tugas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(infoMatapelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoNamaTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoTanggalTenggat, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoStatus))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnKumpul)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uploadTugas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoNamaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoMatapelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoNamaTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(infoTanggalTenggat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(infoStatus))
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadTugas)
                    .addComponent(infoNamaFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnKumpul)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKumpulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKumpulActionPerformed
        if(fileTugas!=null)
        {
            app.sekolah.getSiswa(app.CurrentUser).getDaftarTugas().get(selectedRow).setTelahDikumpulkan(true);
            app.sekolah.getSiswa(app.CurrentUser).getDaftarTugas().get(selectedRow).setFileTugas(fileTugas);
            JOptionPane.showMessageDialog(this, "Tugas telah dikumpulkan");
            app.showListTugasView();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Harap upload file terlebih dahulu");
        }
    }//GEN-LAST:event_btnKumpulActionPerformed

    private void infoNamaTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoNamaTugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoNamaTugasActionPerformed

    private void uploadTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadTugasActionPerformed
       JFileChooser chooser = new JFileChooser();
       chooser.showOpenDialog(null);
       fileTugas = chooser.getSelectedFile();
       String filename = fileTugas.getAbsolutePath();
       infoNamaFile.setText(filename);
    }//GEN-LAST:event_uploadTugasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKumpul;
    private javax.swing.JTextField infoMatapelajaran;
    private javax.swing.JTextField infoNamaFile;
    private javax.swing.JTextField infoNamaTugas;
    private javax.swing.JLabel infoStatus;
    private com.toedter.calendar.JDateChooser infoTanggalTenggat;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton uploadTugas;
    // End of variables declaration//GEN-END:variables
}
